### ISSUE TITLE
Not Working in My Environment

### ISSUE THREAD

**Issue by Choco231** [Bigdasgit/ARIAN#1]
It does not work properly in my environment.
Could you share the details of your development and testing environment?
Thank you!

**Comment by rlawjdgus246** [comment]
Hello,

Thank you for your question!

I have added detailed information about the development and testing environment to the README file.
Please take a look, and feel free to reach out if you encounter any further issues.

**Comment by Bigdasgit** [comment]
Hello,

Thank you for your question!

I have added detailed information about the development and testing environment to the README file.
Please take a look, and feel free to reach out if you encounter any further issues.
