### ISSUE TITLE
Fails to run on my environment

### ISSUE THREAD

**Issue by JJMMPark** [Bigdasgit/ARIAN#2]
I attempted to run ARIAN, but it fails to work properly in my environment. Despite following the setup instructions provided in the repository, issues occur during execution. I am seeking help to resolve this problem.

##Environment##
Operating System: Ubuntu 22.04 LTS (64-bit)
Python Version: 3.8.18
GPU: NVIDIA RTX 3090 (24GB VRAM)
PyTorch Version: 2.0.1

##Steps to Reproduce##
Cloned the repository and installed all required dependencies.

##Observed Behavior##
ARIAN halts or terminates unexpectedly at a certain stage during execution.

##Error Message##
RuntimeError: Expected tensor for argument

##Inquiry##
What are the possible common causes of this issue, and how can I resolve it?
Any guidance or suggestions for troubleshooting would be greatly appreciated.
Thank you for your help!

**Comment by rlawjdgus246** [comment]
Hello,

Thank you for your question!

I have added detailed information about the development and testing environment to the README file.
Please take a look, and feel free to reach out if you encounter any further issues.

**Comment by Bigdasgit** [comment]
Hello,

Thank you for your question!

I have added detailed information about the development and testing environment to the README file.
Please take a look, and feel free to reach out if you encounter any further issues.
