### ISSUE TITLE
Request for Code to Create Dataset for New Data

### ISSUE THREAD

**Issue by mezarara** [Bigdasgit/ARIAN#3]
Hello,

I am interested in running your program on a new dataset. Could you please provide the code or instructions to create the necessary dataset?

Thank you for your assistance!

**Comment by rlawjdgus246** [comment]
Hello,

Thank you for your interest!

I have added a data preprocessing file to the repository.
Please check it out, and feel free to reach out if you have any further questions.

**Comment by Bigdasgit** [comment]
Hello,

Thank you for your interest!

I have added a data preprocessing file to the repository.
Please check it out, and feel free to reach out if you have any further questions.
