### ISSUE TITLE
running RQ 3 issue

### ISSUE THREAD

**Issue by mmaingab** [Bigdasgit/ARIAN#7]
Hello,
Thank for your interesting paper. Could you please advise on how to run the experiments for "RQ 3. Effectiveness of each dependency learner" from your paper? Would it be sufficient to adjust the hyperparameter values, or would it be better to completely remove the corresponding module's code? Your input would be greatly appreciated.

Thank you very much for your help.

Best regards,

**Comment by Bigdasgit** [comment]
Hi, thank you for taking interest in our paper.

To conduct that experiment, you would need to either remove the code corresponding to F2FDL (i.e., fte) or F2SDL (i.e., volume2speed), or add the code corresponding to W2SDL. The uploaded code is for the complete version of our framework, so the code specific to that experiment is not included.

I hope you can understand. Wishing you a Happy New Year!
